- name: Push NETCONF template
  hosts: "{{ passed | default('sdwan') }}"  
  connection: netconf
  tags:
    - netconf
  any_errors_fatal: true
  gather_facts: no
  tasks:
    - meta: refresh_inventory
    
    - netconf_config:
        content: "{{ lookup('template', 'sdwan/netconf/system.j2') }}"